db:
    image: mongo

web:
    build: .
    ports:
       - "3000:80"
    environment:
         port: "80"
         mongoUri: "mongodb://db/app-dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
        - db
